name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List directory contents
      run: ls -R
      working-directory: .


    - name: Build the Docker image
      run: docker build -t otakulounge-image:latest .
      working-directory: .
